root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/casino-royale ."
bin = "tmp/casino-royale"
include_ext = ["go"]
exclude_dir = []
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
