global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.localhost:8080"]
        labels:
          source: "server"
      - targets: ["docker.for.mac.localhost:9090"]
        labels:
          source: "prom_metrics"
